### ISSUE TITLE
The simpleupload component does not handle correctly configuration stanzas

### ISSUE THREAD

**Issue by lives** [ftoulouse/splunk-components-collection#8]
It seems that the goal of the simpleupload component is to be re-usable over multiple splunk apps.
And in order to acheive this, it looks like the elected design is to provide a splunk application '**splunk_components_collection**' containing the simpleupload component.

In other words, in order for an application to use the simpleupload component, the '**splunk_components_collection**' application is required and shall be enabled.

It looks like the 'savePath' and 'tempPath' settings are delegated to the application that uses the simpleupload component. The simpleupload service endpoint currently uses wrong conf files in order to do this.

```settings = splunk.clilib.cli_common.getConfStanza('app', 'ui')```

If the design with the 'splunk_components_collection' dependency **is maintained**, a solution could be :
  - provide the getCurrentApp() to the service endpoint on each calls
  - use a configuration file with the name of the application i.e. 'splunk_components_collection_example.conf'
  - in this configuration file use the stanza [scc_simpleupload] (this allows to keep the same application.conf file and add all other components configuration in it)
  - let the python controller endpoint retreive the configuration stanzas depending on the cherrypy.request.params.get('app')

**Comment by ftoulouse** [comment]
Hi
Actually the goal of the simpleupload component is to be re-usable over multiple splunk apps which wasn't the case until now. Your code is a good solution to achieve that goal, that's why I just merged it. According to your work I'll update the javascript and simplexml codes to be completly dynamic.
Thanks for your feedback, keep the good work!
